// Mapping von unseren Team-Bezeichnungen (siehe src/data/matches.js) zu den
// Namen, wie sie von der football-data.org API geliefert werden. Mehrere
// Aliase pro Team, da sich die Schreibweise je nach Quelle leicht
// unterscheiden kann (z.B. "Czech Republic" vs. "Czechia").

export const teamAliases = {
  'Mexiko': ['Mexico'],
  'Südafrika': ['South Africa'],
  'Südkorea': ['Korea Republic', 'South Korea'],
  'Tschechien': ['Czech Republic', 'Czechia'],
  'Kanada': ['Canada'],
  'Bosnien-Herzegowina': ['Bosnia and Herzegovina'],
  'USA': ['United States', 'USA'],
  'Paraguay': ['Paraguay'],
  'Katar': ['Qatar'],
  'Schweiz': ['Switzerland'],
  'Haiti': ['Haiti'],
  'Schottland': ['Scotland'],
  'Brasilien': ['Brazil'],
  'Marokko': ['Morocco'],
  'Deutschland': ['Germany'],
  'Curaçao': ['Curaçao', 'Curacao'],
  'Niederlande': ['Netherlands'],
  'Japan': ['Japan'],
  'Australien': ['Australia'],
  'Türkei': ['Türkiye', 'Turkey'],
  'Elfenbeinküste': ['Ivory Coast', "Côte d'Ivoire", "Cote d'Ivoire"],
  'Ecuador': ['Ecuador'],
  'Schweden': ['Sweden'],
  'Tunesien': ['Tunisia'],
  'Belgien': ['Belgium'],
  'Ägypten': ['Egypt'],
  'Iran': ['IR Iran', 'Iran'],
  'Neuseeland': ['New Zealand'],
  'Spanien': ['Spain'],
  'Kap Verde': ['Cape Verde', 'Cabo Verde'],
  'Saudi-Arabien': ['Saudi Arabia'],
  'Uruguay': ['Uruguay'],
  'Frankreich': ['France'],
  'Senegal': ['Senegal'],
  'Irak': ['Iraq'],
  'Norwegen': ['Norway'],
  'Argentinien': ['Argentina'],
  'Algerien': ['Algeria'],
  'Österreich': ['Austria'],
  'Jordanien': ['Jordan'],
  'Portugal': ['Portugal'],
  'DR Kongo': ['DR Congo', 'Congo DR', 'Democratic Republic of the Congo', 'DR Congo (Zaire)'],
  'Usbekistan': ['Uzbekistan'],
  'Kolumbien': ['Colombia'],
  'England': ['England'],
  'Kroatien': ['Croatia'],
  'Ghana': ['Ghana'],
  'Panama': ['Panama'],
}
